### ISSUE TITLE
Not Working For Tensorflow 1 tf record

### ISSUE THREAD

**Issue by Nagaraj4896** [sulc/tfrecord-viewer#13]
tfviewer is not working for a model that trained with TensorFlow 1 and it shows the black screen in the browser.

**Comment by sulc** [comment]
Dear Nagaraj, can you please describe your problem in more detail?
1) Are you getting any errors messages when running tfrecord-viewer?
2) You are mentioning a model trained with TF1, but this is just a viewer of annotations. Do you mean data converted to TFRecord with TF1?
3) What is the image format used in your TFRecords? tfrecord-viewer assumes all images are JPEGs. If not, try changing the `get_image` function in `tfviewer.py`.
