### ISSUE TITLE
boxes are misplaced on the image

### ISSUE THREAD

**Issue by flik1337** [sulc/tfrecord-viewer#20]
![38](https://user-images.githubusercontent.com/56709053/202871236-07bc13f1-f1e2-476b-9641-9efe75535e61.jpeg)

Thank you so much for this amazing job! This viewer helps me a lot  :)
But I found the boxes are misplaced on the image.

All feature names are default, and all arguments are default.

**Comment by sulc** [comment]
Hi @flik1337 , it seems that the issue is in your TFRecord dataset, not in the viewer itself.

Looks like your x/y coordinates are swapped (or image rotated?) - a quick hack to try: switch the values for parameters `bbox-xmin-key, bbox-ymin-key` and  `bbox-xmax-key, bbox-ymax-key` :-)
