### ISSUE TITLE
Wrapper for tfrecord viewer

### ISSUE THREAD

**Issue by ahmetcetin** [sulc/tfrecord-viewer#5]
First I really want to thank you a lot for this project. It saved me tons of time. Just wanted to let you know that I've written a wrapper around this project to make it more user-friendly with selection feature. You can see it here:
[Wrapper for tfrecord viewer](https://github.com/ahmetcetin/tfrecord-viewer)

**Comment by sulc** [comment]
Hello Ahmet,
I'm glad my repo is helpful to you.
Your wrapper looks great, I'm looking forward to trying it.
Cheers!
