### ISSUE TITLE
How to enable Debugging mode

### ISSUE THREAD

**Issue by sainisanjay** [sulc/tfrecord-viewer#6]
By default `Debug mode: off` may i know how i can enable this and what are the things i can debug?

**Comment by sulc** [comment]
Hello @sainisanjay,

the console output you're referring to is printed by the Flask web server.
You can have a look at the Flask [Quickstart guide](https://flask.palletsprojects.com/en/1.1.x/quickstart/#debug-mode) to learn more about the Flask debug mode and how to enable it.
In short: running the server in debug mode gives you an interactive debugger and reloads the server every time you save changes to the code.
