### ISSUE TITLE
How to increase line thickness?

### ISSUE THREAD

**Issue by TolgaBkm** [sulc/tfrecord-viewer#8]
Hello,
I have a tfrecord file which contains bounding boxes of planes.
But my image size is quite large (4800 x 2703). So when I visualize them, bounding boxes look thin.
Therefore, my question is that if there is a way to increase the line thickness of bounding boxes.
I guess it is somewhere in `detection_overlay.py` but I wasn't able to point it out.

Thank you!

**Comment by sulc** [comment]
Hi,

indeed, you can add parameter `width` to draw.rectangle (see [PIL.ImageDraw.rectangle](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.rectangle)) in `detection_overlay.py` on [line 97](https://github.com/sulc/tfrecord-viewer/blob/b7a52fcd0acf1829950de2b6c490be67a534fb6c/overlays/detection_overlay.py#L97).
Note: the parameter `width` was not implemented in older versions of PIL, so make sure you have a recent version.

Kind regards
Milan
